### ISSUE TITLE
安装

### ISSUE THREAD

**Issue by PPParticle** [isrc-cas/riscv-vectorized-benchmark-suite#2]
Hi，
Build RISC-V GNU toolchain and QEMU Simulator for rvv-intrinsic branch
按照这个安装方式，无法成功。
利用intrinsic接口编写rvv 1.0需要什么环境呢

**Comment by joy2myself** [comment]
Hi,

请问toolchain安装无法成功具体遇到的是什么问题？

目前支持编译rvv-intrinsic的编译器有RISC-V GNU toolchain的rvv-intrinsic分支，和LLVM upstream的clang，模拟器可以用RISC-V GNU toolchain中对应版本的QEMU。

**Comment by PPParticle** [comment]
Hi,
llvm upstream 
```
clang --target=riscv64-unknown-elf -march=rv64gcv1p0 -menable-experimental-extensions --sysroot=/home/qiao_sh_pudong/RISCV/Bin/riscv64/riscv64-unknown-elf --gcc-toolchain=/home/qiao_sh_pudong/RISCV/Bin/riscv64 print.c -o print1
```
clang-14: error: invalid arch name 'rv64gcv1p0', unsupported version number 1.0 for experimental extension 'v'(this compiler supports 0.10)
```
clang --version
```
clang version 14.0.0 (https://github.com/llvm/llvm-project.git 65d39942dce1a853378c73cca2b4e946a6af7f8b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

**Comment by ksco** [comment]
Clang 现在只支持 rv64gcv0p10，可以参考本仓库 clang 分支中相关的编译命令。

e.g., https://github.com/plctlab/riscv-vectorized-benchmark-suite/blob/clang/_axpy/Makefile#L50

**Comment by PPParticle** [comment]
> Clang 现在只支持 rv64gcv0p10，可以参考本仓库 clang 分支中相关的编译命令。
> 
> e.g., https://github.com/plctlab/riscv-vectorized-benchmark-suite/blob/clang/_axpy/Makefile#L50

那如何使用rvv 1.0 intrinsic呢

**Comment by ksco** [comment]
v0p10 和 v1p0 之间的差异比较小，至少对于本仓库来说，是不影响使用的。如果确实需要 v1p0，只能等 LLVM 正式支持。

**Comment by PPParticle** [comment]
> v0p10 和 v1p0 之间的差异比较小，至少对于本仓库来说，是不影响使用的。如果确实需要 v1p0，只能等 LLVM 正式支持。

好的，谢谢你
